### ISSUE TITLE
add Observatory via CLI using JSON file

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-cli-app#1]
Maybe a command line driving thing? allowing members of telescopes to add their own telescopes config data to the database the UI utilises to process telescropes.

**Comment by DJWalker42** [comment]
Hijacking this issue.

Add a CLI subcommand to allow users to upload their Observatory using a JSON configuration file.

**Comment by DJWalker42** [comment]
[jodrell_bank_alt.json](https://github.com/user-attachments/files/16144128/jodrell_bank_alt.json)

Using the above file to attempt to create a new observatory via the CLI leads to the following error:

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Already had POJO for id (java.lang.Long) [[ObjectId: key=0, type=com.fasterxml.jackson.databind.deser.impl.PropertyBasedObjectIdGenerator, scope=org.ivoa.dm.proposal.prop.Telescope]] (through reference chain: org.ivoa.dm.proposal.prop.Observatory["telescopes"]->java.util.ArrayList[1]->org.ivoa.dm.proposal.prop.Telescope["_id"])
`

However, using the identical json string in the Swagger UI for the API succeeds in creating the Observatory.

This is the relevant implementation detail of the 'createObservatory' command in the CLI:

```
Observatory observatory = parent.mapper.readValue(jsonFile, Observatory.class);
System.out.println(parent.mapper.writeValueAsString(parent.api.createObservatory(observatory)));
```
I don't know how to fix the problem.

**Comment by DJWalker42** [comment]
The `readValue` method of the ObjectMapper is adding '_id: 0' to the Observatory object AND all nested objects, which I think is causing the exception.

**Comment by DJWalker42** [comment]
It appears that it is a problem with objects in nested arrays having the same JsonIdentityInfo property, namely "_id", value even when that value is 0 i.e., create this object.  For objects not in arrays passing "_id" equal to zero is fine.
